config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  before_save :comment_counter

  validates :text, presence: true
  def comment_counter
    post.update(comments_counter: post.comments.all.length)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post, class_name: 'Post'
  before_save :like_counter
end

def like_counter
  post.update(likes_counter: post.likes.all.length)
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, foreign_key: :post_id
  has_many :likes, foreign_key: :post_id
  belongs_to :author, class_name: 'User'
  before_save :post_counter

  validates :title, presence: true, length: { minimum: 1, maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true }, comparison: { greater_than_or_equal_to: 0 }

  def post_counter
    author.update(posts_counter: author.posts.all.length)
  end

  def most_recent_comments
    comments.order(created_at: :desc).limit(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # extend Devise::Models
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :comments, foreign_key: :author_id
  has_many :posts, foreign_key: :author_id
  has_many :likes, foreign_key: :author_id

  validates :name, presence: true
  validates :posts_counter, comparison: { greater_than_or_equal_to: 0 }, numericality: { only_integer: true }

  def most_recent_post
    posts.order(created_at: :desc).limit(3)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email])
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = current_user
    @comment.post_id = params[:post_id]
    if @comment.save
      redirect_to user_post_path(current_user.id, @comment.post_id), notice: 'comment posted successfully'
    else
      render :new, alert: 'Field to post comment. Please try again'
    end
  end

  private

  def comment_params
    params.permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @like = Like.new(post_id: params[:id], author: current_user)
    if @like.save
      redirect_to root_path, notice: 'Post liked'
    else
      render :new, alert: 'An error occured. Please try again'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:posts).find(params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user
    if @post.save
      redirect_to user_path(current_user.id), notice: 'Post saved'
    else

      render :new, alert: 'An error occured'
    end
  end

  def show
    @user = User.find(params[:user_id])
    @posts = Post.find(params[:id])
    @comments = @posts.comments.includes([:author])
  end

  private

  def post_params
    params.require(:post).permit(:author, :title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
# post helper
module PostsHelper
end

app/helpers/users_helper.rb
# user helper
module UsersHelper
end

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_with model: @comments, url: user_post_comments_path, data: {turbo: false} do |form| %>
  <div class="form__container">
    <div class="form_control">
      <%= form.label :text %>
      <%= form.text_area :text %>
    </div>

    <div>
      <%= form.submit "Post Comment" %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogFust</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
  <%= render "shared/flash" %>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts index method</h1>

<%= render "shared/user_card", person: @user %>

<div class="user_show_container">
<% @user.posts.each_with_index do |post, index| %>
  <div class="post_container">
  <h4><%= link_to post.class, user_post_path(@user.id, post.id) %> #<%=index+1%></h4>
  <p><%= post.title %></p>
  <div class="counters">
    <span>Comments: <%= post.comments_counter %></span> 
    <span>Likes: <%= post.likes_counter%> </span>
  </div>
  </div>

  <div class="post_comment_limit">
  <% post.most_recent_comments.includes([:author]).each do |comment|%>
    <p><%= comment.author.name%> : <%= comment.text%></p>
  <% end %>
  </div>
<% end %>

<button>Pagination</button>
<button><%= link_to 'Create a new post', new_user_post_path(@user.id) %></button>
</div>

app/views/posts/new.html.erb
<h1>Form new</h1>

<%= render "shared/form" %>

app/views/posts/show.html.erb
<h1>Posts show method</h1>

<div class="user_show_container">
   <div class="post_container_info">
    <h4><%= @posts.class %> #<%= @user.id %> by <%= @user.name%></h4>
    <span>Comments: <%= @posts.comments_counter%> Likes: <%= @posts.likes_counter%></span>
  </div>

    <div class="post_desc">
      <%= @posts.title%> and 
      <%= @posts.text%>
    </div>

    <div class="post_comment_limit post_comments">
      <% @comments.each do |comment| %>
        <p><%= comment.author.name%> : <%= comment.text%></p>
      <% end %>
    </div>

    <div>
    <button>
      <%= link_to 'Write a comment', new_user_post_comment_path(@user.id, @posts.id) %>
    </button>
    </div>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice]%>
  <div class="notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert]%>
  <div class="alert">
    <%= flash[:alert]%>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= form_with model: @post, url: user_posts_path, data: {turbo: false} do |form| %>
    <% if form.object.errors.any? %>
       <div class="alert alert-danger">
       <% form.object.errors.full_messages.each do |message| %>
       <div><%= message %></div>
       <% end %>
       </div>
     <% end %>
     <div class="form__container">
       <div class="form_control">
         <%= form.label :title %>
         <%= form.text_field :title%>
       </div>
       <div class="form_control">
         <%= form.label :text %>
         <%= form.text_field :text %>
       </div>
       <div>
         <%= form.submit "Create Post"%>
       </div>
     </div>
   <% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar">
  <div class="nav_container">
      <ul class="nav_menu">
    <%= link_to "Navigation", root_path, class: "navbar_brand" %>
        <li class="nav_item">
        <%= link_to "Home", root_path, class: "nav_link active" %>
        </li>
      </ul>
      <ul class="nav_menu">
        <% if user_signed_in? %>
        <li class="nav_item">
        <%= link_to "edit password", edit_user_registration_path, class: "nav_link" %>
        </li>
        <li class="nav_item">
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "nav_link"%>
        </li>
        <% else %>
        <li class="nav_item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav_link" %>
        </li>
        <li class="nav_item">
        <%= link_to "Sign In", new_user_session_path, class: "nav_link" %>
        </li>
        <% end %>
      </ul>
  </div>
</nav> 

app/views/shared/_user_card.html.erb
<div class="user__post">
    <%= image_tag "#{person.photo}" %>

  <div class="user__post__info">
    <h3><%= person.name %></h3>
    <div class="post__num">
    <p> Number of posts: <%= person.posts_counter %></p>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users Index action</h1>

<% @users.each do |person| %>
<%= link_to user_path(person.id) do%>
<%= render partial: "shared/user_card", :locals => {person: person} %>
<% end %>
<% end %>

app/views/users/show.html.erb
<h1>Users show method</h1>

 <%= render "shared/user_card", person: @user%>
<div class="user_show_container">
<div class="user_bio">
  <h3>Bio</h3>
  <p><%= @user.bio %></p>
</div>

<% @user.most_recent_post.each_with_index do |post, index| %>
  <div class="post_container">
  <h4><%= link_to post.class, user_post_path(@user.id, post.id) %> #<%=index+1%></h4>
  <p class="title"><%= post.title %> and <%= post.text%></p>
  <div class="counters">
    <span>Comments: <%= post.comments_counter %></span> 
    <span>Likes: <%= post.likes_counter%> </span>
  </div>
  </div>
<% end %>

<button><%= link_to 'See all posts', user_posts_path(@user.id) %></button>
</div>